name: Rust

on:
  push:
    branches: [ "server-setup-script" ]
  pull_request:
    branches: [ "server-setup-script" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd server_manager && cargo build --verbose
    - name: Run tests
      run: cd server_manager && cargo test --verbose
